import {
  Blocks,
  BookOpen,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  Bug,
  Camera,
  CircuitBoard,
  Code2,
  Cpu,
  GitBranch,
  GraduationCap,
  Lightbulb,
  MessageSquareText,
  Palette,
  PanelsTopLeft,
  Radio,
  Rocket,
  ScanEye,
  ScanSearch,
  Sparkles,
  Terminal,
  Workflow,
  type LucideIcon,
} from "lucide-react";

import type { WorkshopIconKey } from "@/lib/workshops/workshop-data";

export const WORKSHOP_ICON_MAP: Record<WorkshopIconKey, LucideIcon> = {
  bot: Bot,
  brain: BrainCircuit,
  sparkles: Sparkles,
  code: Code2,
  terminal: Terminal,
  cpu: Cpu,
  "circuit-board": CircuitBoard,
  "graduation-cap": GraduationCap,
  briefcase: BriefcaseBusiness,
  workflow: Workflow,
  lightbulb: Lightbulb,
  rocket: Rocket,
  "book-open": BookOpen,
  bug: Bug,
  "git-branch": GitBranch,
  camera: Camera,
  radio: Radio,
  palette: Palette,
  "message-square-text": MessageSquareText,
  "panels-top-left": PanelsTopLeft,
  "scan-search": ScanSearch,
  blocks: Blocks,
  "scan-eye": ScanEye,
};
